
name: Docker Build

on:
  push:
    branches: [ "main" ]
    
jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t dockerimage .
