
name: Docker Build

on:
  push:
    branches: [ "main" ]
    
jobs:
  docker-build:
    runs-on: self-hosted
    
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: build docker image
        run: docker build -t ravindra9999/github_actions:latest .
        
      - name: push docker image
        run: docker push ravindra9999/github_actions:latest
      
      - name: logout from docker hub
        run: docker logout 
